create table pet (
	id bigint generated by default as identity (start with 1),
	adopted varchar(1) not null,
	stf boolean,
	vaccinated varchar(1) not null,
	name varchar(255) not null,
	sex varchar(255) not null,
	primary key (id)
);